name: Lint
on: [push]
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install libdbus-1-dev pkg-config
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features -D warnings
